"""Step 3 -- the conformal manifold via Leigh-Strassler / GKSTW counting.

The dimension of the conformal manifold of an N=1 SCFT is, by Green-
Komargodski-Seiberg-Tachikawa-Wecht, the number of marginal couplings modulo
the complexified continuous global symmetry:

    dim_C M_conf = #(marginal couplings) - dim_C G_F   (generic, free quotient).

For the C^3/Gamma orbifold theories this evaluates to a clean closed form.
The marginal couplings are the gauge couplings (one per node) together with the
cubic Leigh-Strassler superpotential couplings; the broken global symmetry is
generated by the U(1)'s rotating the orbifold-projected bifundamentals.  The
net count is governed by how the three holomorphic coordinates of C^3 are left
fixed by the group elements:

    fix_Q(g) = # unit eigenvalues of g acting on C^3

    dim_C M_conf = ( 1/|Gamma| ... )  ->   sum_{g in Gamma} fix_Q(g)  -  1

(faithful Gamma, connected quiver).  Equivalently, via Burnside,

    sum_{g} fix_Q(g) = sum over the holomorphic directions of the number of
    group elements fixing that direction,

which for a diagonal cyclic action Z_K with weights (a,b,c) is exactly
gcd(K,a)+gcd(K,b)+gcd(K,c), recovering

    dim_C M_conf = gcd(K,a) + gcd(K,b) + gcd(K,c) - 1.

The result is independent of the number of branes N.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd

from .groups import MatrixGroup


@dataclass
class ConformalResult:
    group_name: str
    order: int
    fixed_sum: int            # S = sum_{g} fix_Q(g)
    dim_conf: int             # dim_C of the conformal manifold = S - 1
    per_direction: list[int] | None = None  # for diagonal/abelian actions
    note: str = ""

    def __str__(self) -> str:
        lines = [
            f"Conformal manifold of C^3/{self.group_name}  (N D3-branes)",
            f"  |Gamma|                       = {self.order}",
            f"  S = sum_g fix_Q(g)            = {self.fixed_sum}",
        ]
        if self.per_direction is not None:
            lines.append(
                f"  per-coordinate fixed counts  = {self.per_direction} "
                f"(sum {sum(self.per_direction)})")
        lines.append(
            f"  dim_C M_conf = S - 1          = {self.dim_conf}   "
            "(independent of N)")
        if self.note:
            lines.append(f"  note: {self.note}")
        return "\n".join(lines)


def conformal_manifold_dim(group: MatrixGroup) -> ConformalResult:
    """Closed-form conformal-manifold dimension for C^3/Gamma."""
    S = 0
    for g in group.elements:
        S += group.fix_Q(g)

    per_dir = None
    note = ""
    if group.is_abelian():
        per_dir = _abelian_per_direction(group)
        if per_dir is not None and sum(per_dir) != S:
            # fall back silently to the basis-independent S if the diagonal
            # read-off disagrees (e.g. non-diagonal abelian presentation)
            per_dir = None

    if not _quiver_connected_hint(group):
        note = ("Gamma may be non-faithful / quiver disconnected; the "
                "'-1' (single overall U(1)) can change -- treat S-1 as the "
                "faithful, connected-quiver value.")

    return ConformalResult(
        group_name=group.name,
        order=group.order,
        fixed_sum=S,
        dim_conf=S - 1,
        per_direction=per_dir,
        note=note,
    )


def _abelian_per_direction(group: MatrixGroup) -> list[int] | None:
    """If the elements are simultaneously diagonal, count, per coordinate axis,
    how many group elements leave that axis fixed (eigenvalue 1)."""
    import numpy as np
    counts = [0, 0, 0]
    for g in group.elements:
        if not np.allclose(g, np.diag(np.diag(g)), atol=1e-6):
            return None
        d = np.diag(g)
        for k in range(3):
            if np.isclose(d[k], 1.0, atol=1e-5):
                counts[k] += 1
    return counts


def _quiver_connected_hint(group: MatrixGroup) -> bool:
    """Cheap faithfulness proxy: the action is faithful iff only the identity
    fixes all of C^3."""
    import numpy as np
    fixers_all = sum(1 for g in group.elements
                     if np.allclose(g, np.eye(3), atol=1e-6))
    return fixers_all == 1


def cyclic_closed_form(n: int, weights: tuple[int, int, int]) -> int:
    """Reference closed form for the diagonal cyclic case (for tests)."""
    a, b, c = weights
    return gcd(n, a) + gcd(n, b) + gcd(n, c) - 1
